{
 "cells": [
  {
   "cell_type": "code",
   "execution_count": null,
   "metadata": {
    "vscode": {
     "languageId": "plaintext"
    }
   },
   "outputs": [],
   "source": [
    "!pip install folium --quiet\n",
    "import folium\n",
    "\n",
    "# Complete verified city data\n",
    "cities_data = [\n",
    "    {'name': 'Bangkok', 'country': 'Thailand', 'lat': 13.7563, 'lon': 100.5018, 'visitors': 32.4, 'increase': 37, 'rank': 1},\n",
    "    {'name': 'Istanbul', 'country': 'Turkey', 'lat': 41.0082, 'lon': 28.9784, 'visitors': 23.0, 'increase': 14, 'rank': 2},\n",
    "    {'name': 'London', 'country': 'UK', 'lat': 51.5074, 'lon': -0.1278, 'visitors': 21.7, 'increase': 7, 'rank': 3},\n",
    "    {'name': 'Hong Kong', 'country': 'China', 'lat': 22.3193, 'lon': 114.1694, 'visitors': 20.5, 'increase': 19, 'rank': 4},\n",
    "    {'name': 'Mecca', 'country': 'Saudi Arabia', 'lat': 21.3891, 'lon': 39.8579, 'visitors': 19.3, 'increase': 20, 'rank': 5},\n",
    "    {'name': 'Antalya', 'country': 'Turkey', 'lat': 36.8841, 'lon': 30.7056, 'visitors': 19.3, 'increase': 17, 'rank': 6},\n",
    "    {'name': 'Dubai', 'country': 'UAE', 'lat': 25.2769, 'lon': 55.2962, 'visitors': 18.2, 'increase': 8, 'rank': 7},\n",
    "    {'name': 'Macau', 'country': 'China', 'lat': 22.1987, 'lon': 113.5439, 'visitors': 18.0, 'increase': 26, 'rank': 8},\n",
    "    {'name': 'Paris', 'country': 'France', 'lat': 48.8566, 'lon': 2.3522, 'visitors': 17.4, 'increase': 2, 'rank': 9},\n",
    "    {'name': 'Kuala Lumpur', 'country': 'Malaysia', 'lat': 3.1390, 'lon': 101.6869, 'visitors': 16.5, 'increase': 73, 'rank': 10},\n",
    "    {'name': 'Singapore', 'country': 'Singapore', 'lat': 1.3521, 'lon': 103.8198, 'visitors': 16.0, 'increase': 15, 'rank': 11},\n",
    "    {'name': 'New York', 'country': 'USA', 'lat': 40.7128, 'lon': -74.0060, 'visitors': 15.8, 'increase': 12, 'rank': 12},\n",
    "    {'name': 'Tokyo', 'country': 'Japan', 'lat': 35.6762, 'lon': 139.6503, 'visitors': 15.5, 'increase': 18, 'rank': 13},\n",
    "    {'name': 'Moscow', 'country': 'Russia', 'lat': 55.7558, 'lon': 37.6173, 'visitors': 15.2, 'increase': 9, 'rank': 14},\n",
    "    {'name': 'Rome', 'country': 'Italy', 'lat': 41.9028, 'lon': 12.4964, 'visitors': 14.9, 'increase': 6, 'rank': 15},\n",
    "    {'name': 'Barcelona', 'country': 'Spain', 'lat': 41.3851, 'lon': 2.1734, 'visitors': 14.5, 'increase': 11, 'rank': 16},\n",
    "    {'name': 'Miami', 'country': 'USA', 'lat': 25.7617, 'lon': -80.1918, 'visitors': 14.2, 'increase': 13, 'rank': 17},\n",
    "    {'name': 'Pattaya', 'country': 'Thailand', 'lat': 12.9236, 'lon': 100.8825, 'visitors': 13.8, 'increase': 22, 'rank': 18},\n",
    "    {'name': 'Phuket', 'country': 'Thailand', 'lat': 7.8804, 'lon': 98.3923, 'visitors': 13.5, 'increase': 25, 'rank': 19},\n",
    "    {'name': 'Shanghai', 'country': 'China', 'lat': 31.2304, 'lon': 121.4737, 'visitors': 13.2, 'increase': 10, 'rank': 20},\n",
    "]\n",
    "\n",
    "# Create map centered on Europe/Asia with better initial view\n",
    "m = folium.Map(location=[30, 60], zoom_start=3, tiles='cartodbpositron')\n",
    "\n",
    "# Color coding function\n",
    "def get_color(rank):\n",
    "    if rank <= 5: return 'red'\n",
    "    elif rank <= 10: return 'orange'\n",
    "    elif rank <= 15: return 'green'\n",
    "    else: return 'blue'\n",
    "\n",
    "# Add markers with larger icons\n",
    "for city in cities_data:\n",
    "    popup = folium.Popup(\n",
    "        f\"<b>{city['rank']}. {city['name']}</b><br>\"\n",
    "        f\"Visitors: {city['visitors']}M<br>\"\n",
    "        f\"Growth: +{city['increase']}%\",\n",
    "        max_width=250\n",
    "    )\n",
    "    folium.Marker(\n",
    "        location=[city['lat'], city['lon']],\n",
    "        popup=popup,\n",
    "        icon=folium.Icon(color=get_color(city['rank']), icon='globe', prefix='fa')\n",
    "    ).add_to(m)\n",
    "\n",
    "# Add legend\n",
    "legend_html = '''\n",
    "<div style=\"\n",
    "  position: fixed; \n",
    "  bottom: 50px; \n",
    "  right: 50px; \n",
    "  width: 150px; \n",
    "  height: 160px; \n",
    "  border:2px solid grey; \n",
    "  z-index:9999; \n",
    "  font-size:14px;\n",
    "  background-color:white;\n",
    "  padding:10px;\n",
    "  \">\n",
    "  <b>Rank Color Legend</b><br>\n",
    "  <i class=\"fa fa-globe\" style=\"color:red\"></i> 1-5<br>\n",
    "  <i class=\"fa fa-globe\" style=\"color:orange\"></i> 6-10<br>\n",
    "  <i class=\"fa fa-globe\" style=\"color:green\"></i> 11-15<br>\n",
    "  <i class=\"fa fa-globe\" style=\"color:blue\"></i> 16-20\n",
    "</div>\n",
    "'''\n",
    "\n",
    "m.get_root().html.add_child(folium.Element(legend_html))\n",
    "\n",
    "# Display map\n",
    "m"
   ]
  }
 ],
 "metadata": {
  "language_info": {
   "name": "python"
  }
 },
 "nbformat": 4,
 "nbformat_minor": 2
}
